// frontend-react/src/pages/EventDetailPage.jsx
import { useEffect, useState } from "react";
import {
  Alert,
  AppBar,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Container,
  Divider,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material";
import { Link as RouterLink, useNavigate, useParams } from "react-router-dom";
import { deleteEvent, getEvent } from "../services/eventsApi";

function formatDate(value) {
  if (!value) return "-";
  return new Intl.DateTimeFormat("pt-BR", {
    dateStyle: "full",
    timeStyle: "short",
  }).format(new Date(value));
}

export function EventDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [event, setEvent] = useState(null);

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      setError("");
      try {
        const result = await getEvent(id);
        setEvent(result);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [id]);

  const handleDelete = async () => {
    if (!event) return;
    const confirmed = window.confirm(`Excluir o evento "${event.title}"?`);
    if (!confirmed) return;

    try {
      await deleteEvent(event.id);
      navigate("/eventos");
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <Box>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            TeamMeet Planner
          </Typography>
          <Button color="inherit" component={RouterLink} to="/eventos">
            Voltar para lista
          </Button>
        </Toolbar>
      </AppBar>

      <Container maxWidth="md" sx={{ py: 4 }}>
        <Card>
          <CardContent>
            {loading ? (
              <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
                <CircularProgress />
              </Box>
            ) : (
              <Stack gap={2}>
                {error && <Alert severity="error">{error}</Alert>}

                {event && (
                  <>
                    <Typography variant="h5">{event.title}</Typography>
                    <Typography color="text.secondary">{event.location}</Typography>
                    <Divider />

                    <Typography>
                      <strong>Início:</strong> {formatDate(event.startDate)}
                    </Typography>
                    <Typography>
                      <strong>Término:</strong> {formatDate(event.endDate)}
                    </Typography>
                    <Typography>
                      <strong>Status:</strong> {event.status}
                    </Typography>
                    <Typography>
                      <strong>Organizador:</strong> {event.organizerName || "-"}
                    </Typography>
                    <Typography>
                      <strong>E-mail:</strong> {event.organizerEmail}
                    </Typography>
                    <Typography>
                      <strong>Categoria:</strong> {event.category?.name || "Sem categoria"}
                    </Typography>

                    <Stack direction="row" justifyContent="flex-end" gap={1}>
                      <Button component={RouterLink} to={`/eventos/${event.id}/edit`}>
                        Editar
                      </Button>
                      <Button color="error" onClick={handleDelete}>
                        Excluir
                      </Button>
                    </Stack>
                  </>
                )}
              </Stack>
            )}
          </CardContent>
        </Card>
      </Container>
    </Box>
  );
}

// frontend-vue/src/pages/EventDetailPage.vue
<template>
  <v-container class="py-8" style="max-width: 900px;">
    <v-card class="pa-6" elevation="4">
      <v-card-title class="text-h6 mb-2">Event details</v-card-title>

      <v-alert v-if="error" type="error" variant="tonal" class="mb-4">
        {{ error }}
      </v-alert>

      <v-progress-linear v-if="loading" indeterminate color="primary" class="mb-4" />

      <v-list v-if="event">
        <v-list-item title="Title" :subtitle="event.title" />
        <v-list-item title="Start" :subtitle="formatDate(event.startDate)" />
        <v-list-item title="End" :subtitle="formatDate(event.endDate)" />
        <v-list-item title="Status" :subtitle="formatStatus(event.status)" />
        <v-list-item title="Organizer" :subtitle="event.organizerEmail" />
        <v-list-item title="Location" :subtitle="event.location" />
        <v-list-item title="Category" :subtitle="event.category || 'Not informed'" />
        <v-list-item title="Created" :subtitle="formatDate(event.createdAt)" />
      </v-list>

      <div class="d-flex align-center gap-3 mt-4">
        <v-btn variant="text" @click="goBack">Back</v-btn>
        <v-spacer />
        <v-btn color="primary" variant="text" @click="goToEdit">Edit</v-btn>
        <v-btn color="error" variant="text" @click="confirmDelete">Delete</v-btn>
      </div>
    </v-card>
  </v-container>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { deleteEvent, getEvent } from '../services/eventsApi';

const route = useRoute();
const router = useRouter();

const event = ref(null);
const loading = ref(false);
const error = ref('');

function formatDate(value) {
  if (!value) return '-';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '-';
  return date.toLocaleString('pt-BR');
}

function formatStatus(status) {
  if (status === 'cancelled') return 'Cancelled';
  return 'Scheduled';
}

async function loadEvent() {
  loading.value = true;
  error.value = '';
  try {
    event.value = await getEvent(route.params.id);
  } catch (err) {
    error.value = err.message || 'Failed to load event';
  } finally {
    loading.value = false;
  }
}

function goBack() {
  router.push({ name: 'events' });
}

function goToEdit() {
  router.push({ name: 'event-edit', params: { id: route.params.id } });
}

async function confirmDelete() {
  if (!event.value) return;
  const ok = window.confirm(`Delete event "${event.value.title}"?`);
  if (!ok) return;
  try {
    await deleteEvent(event.value.id);
    router.push({ name: 'events' });
  } catch (err) {
    error.value = err.message || 'Failed to delete event';
  }
}

onMounted(() => {
  loadEvent();
});
</script>

<style scoped>
.gap-3 {
  gap: 12px;
}
</style>
