// frontend-vue/src/pages/CategoriesPage.vue
<template>
  <v-container class="py-8" style="max-width: 900px">
    <div class="d-flex align-center justify-space-between mb-4">
      <div>
        <div class="text-h5">Categorias</div>
        <div class="text-body-2 text-medium-emphasis">
          Crie, renomeie e remova categorias de eventos.
        </div>
      </div>
      <v-btn variant="text" :to="{ name: 'events-list' }">Voltar</v-btn>
    </div>

    <v-card elevation="4" class="mb-4">
      <v-card-text>
        <div class="text-subtitle-1 mb-2">Nova categoria</div>
        <div class="d-flex flex-wrap gap-3 align-center">
          <v-text-field
            v-model="newName"
            label="Nome da categoria"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 280px"
          />
          <v-btn color="primary" @click="createCategory" :loading="creating">
            Criar
          </v-btn>
        </div>
      </v-card-text>
    </v-card>

    <v-card elevation="4">
      <v-card-text>
        <v-alert v-if="error" type="error" variant="tonal" class="mb-4">
          {{ error }}
        </v-alert>

        <v-table density="comfortable">
          <thead>
            <tr>
              <th>Nome</th>
              <th class="text-right">Acoes</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!loading && categories.length === 0">
              <td colspan="2" class="text-medium-emphasis">
                Nenhuma categoria cadastrada.
              </td>
            </tr>
            <tr v-for="cat in categories" :key="cat.id">
              <td class="font-weight-medium">{{ cat.name }}</td>
              <td class="text-right">
                <v-btn size="small" variant="text" @click="openEdit(cat)">
                  Renomear
                </v-btn>
                <v-btn
                  size="small"
                  variant="text"
                  color="error"
                  @click="openDelete(cat)"
                >
                  Remover
                </v-btn>
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-card-text>
    </v-card>

    <v-dialog v-model="editDialog" max-width="520">
      <v-card>
        <v-card-title>Renomear categoria</v-card-title>
        <v-card-text>
          <v-text-field
            v-model="editName"
            label="Nome da categoria"
            variant="outlined"
            density="comfortable"
          />
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="editDialog = false">Cancelar</v-btn>
          <v-btn color="primary" @click="saveEdit" :loading="editing">
            Salvar
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog v-model="deleteDialog" max-width="520">
      <v-card>
        <v-card-title>Confirmar remocao</v-card-title>
        <v-card-text>
          Tem certeza que deseja remover a categoria
          <strong>{{ deleting?.name }}</strong>?
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="deleteDialog = false">Cancelar</v-btn>
          <v-btn color="error" @click="confirmDelete" :loading="deletingLoading">
            Remover
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { categoriesApi } from "../services/categoriesApi";

const categories = ref([]);
const loading = ref(false);
const error = ref("");

const newName = ref("");
const creating = ref(false);

const editDialog = ref(false);
const editing = ref(false);
const editingCategory = ref(null);
const editName = ref("");

const deleteDialog = ref(false);
const deleting = ref(null);
const deletingLoading = ref(false);

function validateName(name) {
  const normalized = name.trim().replace(/\s+/g, " ");
  if (normalized.length < 2 || normalized.length > 60) {
    return "Nome deve ter entre 2 e 60 caracteres.";
  }
  return null;
}

async function fetchCategories() {
  loading.value = true;
  error.value = "";
  try {
    categories.value = await categoriesApi.list();
  } catch (e) {
    error.value = e?.message || "Erro ao carregar categorias.";
  } finally {
    loading.value = false;
  }
}

async function createCategory() {
  error.value = "";
  const validation = validateName(newName.value || "");
  if (validation) {
    error.value = validation;
    return;
  }

  creating.value = true;
  try {
    await categoriesApi.create({ name: newName.value });
    newName.value = "";
    await fetchCategories();
  } catch (e) {
    error.value = e?.message || "Erro ao criar categoria.";
  } finally {
    creating.value = false;
  }
}

function openEdit(cat) {
  editingCategory.value = cat;
  editName.value = cat.name;
  editDialog.value = true;
}

async function saveEdit() {
  if (!editingCategory.value) return;
  error.value = "";
  const validation = validateName(editName.value || "");
  if (validation) {
    error.value = validation;
    return;
  }

  editing.value = true;
  try {
    await categoriesApi.update(editingCategory.value.id, {
      name: editName.value,
    });
    editDialog.value = false;
    editingCategory.value = null;
    await fetchCategories();
  } catch (e) {
    error.value = e?.message || "Erro ao renomear categoria.";
  } finally {
    editing.value = false;
  }
}

function openDelete(cat) {
  deleting.value = cat;
  deleteDialog.value = true;
}

async function confirmDelete() {
  if (!deleting.value) return;
  error.value = "";
  deletingLoading.value = true;
  try {
    await categoriesApi.remove(deleting.value.id);
    deleteDialog.value = false;
    deleting.value = null;
    await fetchCategories();
  } catch (e) {
    error.value = e?.message || "Erro ao remover categoria.";
  } finally {
    deletingLoading.value = false;
  }
}

onMounted(() => {
  fetchCategories();
});
</script>

<style scoped>
.gap-3 {
  gap: 12px;
}
</style>

// frontend-react/src/features/categories/pages/CategoriesPage.jsx
import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TextField,
  Typography,
} from "@mui/material";
import { CategoriesApi } from "../services/categoriesApi";

const categoriesApi = new CategoriesApi();

function validateName(name) {
  const normalized = name.trim();

  if (normalized.length < 2 || normalized.length > 60) {
    return "Nome da categoria deve ter entre 2 e 60 caracteres";
  }

  return "";
}

export function CategoriesPage() {
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [newCategoryName, setNewCategoryName] = useState("");
  const [savingNew, setSavingNew] = useState(false);
  const [editingCategory, setEditingCategory] = useState(null);
  const [editingName, setEditingName] = useState("");
  const [editingError, setEditingError] = useState("");
  const [savingEdit, setSavingEdit] = useState(false);
  const [deletingCategory, setDeletingCategory] = useState(null);
  const [deleting, setDeleting] = useState(false);

  const newNameError = useMemo(() => validateName(newCategoryName), [newCategoryName]);

  const load = async () => {
    setLoading(true);
    setError("");

    try {
      const response = await categoriesApi.list();
      setCategories(response);
    } catch (err) {
      setError(err.message || "Falha ao carregar categorias");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const handleCreate = async (event) => {
    event.preventDefault();

    const validationError = validateName(newCategoryName);
    if (validationError) {
      setError(validationError);
      return;
    }

    setSavingNew(true);
    setError("");

    try {
      await categoriesApi.create({ name: newCategoryName.trim() });
      setNewCategoryName("");
      await load();
    } catch (err) {
      setError(err.message || "Falha ao criar categoria");
    } finally {
      setSavingNew(false);
    }
  };

  const handleOpenEdit = (category) => {
    setEditingCategory(category);
    setEditingName(category.name);
    setEditingError("");
  };

  const handleSaveEdit = async () => {
    if (!editingCategory) {
      return;
    }

    const validationError = validateName(editingName);
    if (validationError) {
      setEditingError(validationError);
      return;
    }

    setSavingEdit(true);
    setEditingError("");

    try {
      await categoriesApi.update(editingCategory.id, { name: editingName.trim() });
      setEditingCategory(null);
      setEditingName("");
      await load();
    } catch (err) {
      setEditingError(err.message || "Falha ao renomear categoria");
    } finally {
      setSavingEdit(false);
    }
  };

  const handleDelete = async () => {
    if (!deletingCategory) {
      return;
    }

    setDeleting(true);
    setError("");

    try {
      await categoriesApi.remove(deletingCategory.id);
      setDeletingCategory(null);
      await load();
    } catch (err) {
      setError(err.message || "Falha ao remover categoria");
    } finally {
      setDeleting(false);
    }
  };

  return (
    <Stack spacing={3}>
      <Typography variant="h4">Categorias</Typography>

      <Paper sx={{ p: 2 }}>
        <Stack
          component="form"
          direction={{ xs: "column", md: "row" }}
          spacing={2}
          onSubmit={handleCreate}
        >
          <TextField
            label="Nova categoria"
            value={newCategoryName}
            onChange={(event) => setNewCategoryName(event.target.value)}
            fullWidth
            error={Boolean(newCategoryName) && Boolean(newNameError)}
            helperText={newCategoryName ? newNameError : ""}
          />
          <Button type="submit" variant="contained" disabled={savingNew || Boolean(newNameError)}>
            {savingNew ? "Salvando..." : "Adicionar"}
          </Button>
        </Stack>
      </Paper>

      {error && <Alert severity="error">{error}</Alert>}

      <Paper>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Nome</TableCell>
              <TableCell align="right">Ações</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {loading && (
              <TableRow>
                <TableCell colSpan={2}>Carregando categorias...</TableCell>
              </TableRow>
            )}

            {!loading && categories.length === 0 && (
              <TableRow>
                <TableCell colSpan={2}>Nenhuma categoria cadastrada.</TableCell>
              </TableRow>
            )}

            {!loading &&
              categories.map((category) => (
                <TableRow key={category.id} hover>
                  <TableCell>{category.name}</TableCell>
                  <TableCell align="right">
                    <Stack direction="row" spacing={1} justifyContent="flex-end">
                      <Button size="small" onClick={() => handleOpenEdit(category)}>
                        Renomear
                      </Button>
                      <Button
                        size="small"
                        color="error"
                        onClick={() => setDeletingCategory(category)}
                      >
                        Remover
                      </Button>
                    </Stack>
                  </TableCell>
                </TableRow>
              ))}
          </TableBody>
        </Table>
      </Paper>

      <Dialog open={Boolean(editingCategory)} onClose={() => setEditingCategory(null)}>
        <DialogTitle>Renomear categoria</DialogTitle>
        <DialogContent>
          <Box sx={{ pt: 1 }}>
            <TextField
              label="Nome"
              value={editingName}
              onChange={(event) => setEditingName(event.target.value)}
              fullWidth
              autoFocus
              error={Boolean(editingError)}
              helperText={editingError}
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditingCategory(null)} disabled={savingEdit}>
            Cancelar
          </Button>
          <Button onClick={handleSaveEdit} disabled={savingEdit}>
            {savingEdit ? "Salvando..." : "Salvar"}
          </Button>
        </DialogActions>
      </Dialog>

      <Dialog open={Boolean(deletingCategory)} onClose={() => setDeletingCategory(null)}>
        <DialogTitle>Remover categoria</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Deseja remover a categoria "{deletingCategory?.name}"?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeletingCategory(null)} disabled={deleting}>
            Cancelar
          </Button>
          <Button onClick={handleDelete} color="error" disabled={deleting}>
            {deleting ? "Removendo..." : "Remover"}
          </Button>
        </DialogActions>
      </Dialog>
    </Stack>
  );
}
