// frontend-vue/src/pages/EventsListPage.vue
<template>
  <v-container class="py-8" style="max-width: 1100px">
    <div class="d-flex align-center justify-space-between mb-4">
      <div>
        <div class="text-h5">Eventos</div>
        <div class="text-body-2 text-medium-emphasis">
          Busca por título, paginação e ordenação.
        </div>
      </div>
      <v-btn color="primary" :to="{ name: 'events-new' }">Novo evento</v-btn>
    </div>

    <v-card elevation="4">
      <v-card-text>
        <div class="d-flex flex-wrap gap-3 align-center">
          <v-text-field
            v-model="q"
            label="Buscar por título"
            prepend-inner-icon="mdi-magnify"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 260px"
          />

          <v-select
            v-model="sortBy"
            :items="sortByItems"
            item-title="title"
            item-value="value"
            label="Ordenar por"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 200px"
          />

          <v-select
            v-model="sortDir"
            :items="sortDirItems"
            item-title="title"
            item-value="value"
            label="Direção"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 160px"
          />

          <v-select
            v-model="size"
            :items="[5, 10, 20, 50]"
            label="Tamanho da página"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 170px"
          />

          <v-select
            v-model="categoryId"
            :items="categoryItems"
            item-title="title"
            item-value="value"
            label="Categoria"
            variant="outlined"
            density="comfortable"
            hide-details
            style="min-width: 220px"
          />

          <v-spacer />

          <v-btn variant="tonal" @click="refresh" :loading="loading">
            Atualizar
          </v-btn>
        </div>

        <v-divider class="my-4" />

        <v-alert v-if="error" type="error" variant="tonal" class="mb-4">
          {{ error }}
        </v-alert>

        <v-table density="comfortable">
          <thead>
            <tr>
              <th>Título</th>
              <th>Categoria</th>
              <th>Início</th>
              <th>Término</th>
              <th>Status</th>
              <th>Organizador</th>
              <th class="text-right">Ações</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="!loading && items.length === 0">
              <td colspan="7" class="text-medium-emphasis">
                Nenhum evento encontrado.
              </td>
            </tr>
            <tr v-for="ev in items" :key="ev.id">
              <td class="font-weight-medium">{{ ev.title }}</td>
              <td>{{ ev.category?.name || "-" }}</td>
              <td>{{ formatDateTime(ev.startDate) }}</td>
              <td>{{ formatDateTime(ev.endDate) }}</td>
              <td>
                <v-chip
                  size="small"
                  :color="ev.status === 'canceled' ? 'error' : 'success'"
                  variant="tonal"
                >
                  {{ ev.status === "canceled" ? "Cancelado" : "Agendado" }}
                </v-chip>
              </td>
              <td>{{ ev.organizerEmail }}</td>
              <td class="text-right">
                <v-btn
                  size="small"
                  variant="text"
                  :to="{ name: 'events-detail', params: { id: ev.id } }"
                >
                  Ver
                </v-btn>
                <v-btn
                  size="small"
                  variant="text"
                  :to="{ name: 'events-edit', params: { id: ev.id } }"
                >
                  Editar
                </v-btn>
                <v-btn
                  size="small"
                  variant="text"
                  color="error"
                  @click="openDelete(ev)"
                >
                  Excluir
                </v-btn>
              </td>
            </tr>
          </tbody>
        </v-table>

        <div class="d-flex align-center justify-space-between mt-4">
          <div class="text-body-2 text-medium-emphasis">Total: {{ total }}</div>
          <v-pagination
            v-model="page"
            :length="pageCount"
            :total-visible="7"
            density="comfortable"
          />
        </div>
      </v-card-text>
    </v-card>

    <v-dialog v-model="deleteDialog" max-width="520">
      <v-card>
        <v-card-title>Confirmar exclusão</v-card-title>
        <v-card-text>
          Tem certeza que deseja excluir o evento
          <strong>{{ deleting?.title }}</strong
          >?
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="deleteDialog = false">Cancelar</v-btn>
          <v-btn
            color="error"
            @click="confirmDelete"
            :loading="deletingLoading"
          >
            Excluir
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref, watch } from "vue";
import { eventsApi } from "../services/eventsApi";
import { categoriesApi } from "../services/categoriesApi";
import { formatDateTime } from "../utils/dateTime";

const loading = ref(false);
const error = ref("");

const items = ref([]);
const total = ref(0);

const page = ref(1);
const size = ref(10);
const q = ref("");

const sortBy = ref("startDate");
const sortDir = ref("ASC");

const categoryId = ref(null);
const categories = ref([]);

const categoryItems = computed(() => [
  { title: "Todas", value: null },
  ...categories.value.map((c) => ({ title: c.name, value: c.id })),
]);

const sortByItems = [
  { title: "Data de início", value: "startDate" },
  { title: "Data de criação", value: "createdAt" },
];

const sortDirItems = [
  { title: "Crescente (ASC)", value: "ASC" },
  { title: "Decrescente (DESC)", value: "DESC" },
];

const pageCount = computed(() =>
  Math.max(1, Math.ceil(total.value / size.value)),
);

let qTimer = null;
watch(q, () => {
  // Debounce simples para não bater na API a cada tecla.
  if (qTimer) clearTimeout(qTimer);
  qTimer = setTimeout(() => {
    page.value = 1;
    refresh();
  }, 300);
});

watch([page, size, sortBy, sortDir], () => {
  refresh();
});

watch(categoryId, () => {
  page.value = 1;
  refresh();
});

async function refresh() {
  loading.value = true;
  error.value = "";
  try {
    const data = await eventsApi.list({
      page: page.value,
      size: size.value,
      q: q.value,
      sortBy: sortBy.value,
      sortDir: sortDir.value,
      categoryId: categoryId.value,
    });

    items.value = data.items;
    total.value = data.total;

    // Se o usuário reduziu size e a página atual ficou inválida.
    if (page.value > pageCount.value) {
      page.value = pageCount.value;
    }
  } catch (e) {
    error.value = e?.message || "Erro ao carregar eventos.";
  } finally {
    loading.value = false;
  }
}

const deleteDialog = ref(false);
const deleting = ref(null);
const deletingLoading = ref(false);

function openDelete(ev) {
  deleting.value = ev;
  deleteDialog.value = true;
}

async function confirmDelete() {
  if (!deleting.value) return;
  deletingLoading.value = true;
  try {
    await eventsApi.remove(deleting.value.id);
    deleteDialog.value = false;
    deleting.value = null;
    refresh();
  } catch (e) {
    error.value = e?.message || "Erro ao excluir evento.";
  } finally {
    deletingLoading.value = false;
  }
}

onMounted(() => {
  (async () => {
    try {
      categories.value = await categoriesApi.list();
    } catch {
      // Sem bloquear a tela de eventos caso categorias estejam indisponíveis.
      categories.value = [];
    }

    refresh();
  })();
});
</script>

<style scoped>
.gap-3 {
  gap: 12px;
}
</style>

// frontend-react/src/features/events/pages/EventsListPage.jsx
﻿import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  FormControl,
  InputLabel,
  MenuItem,
  Paper,
  Select,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TextField,
  Typography,
} from "@mui/material";
import { Link as RouterLink, useNavigate } from "react-router-dom";
import { useEventsApi } from "../providers/EventsApiProvider";
import { toDisplayDateTime } from "../utils/date";

const DEFAULT_QUERY = {
  page: 1,
  size: 5,
  search: "",
  sortBy: "startDate",
  sortDir: "asc",
  categoryId: "",
};

export function EventsListPage() {
  const api = useEventsApi();
  const navigate = useNavigate();

  const [query, setQuery] = useState(DEFAULT_QUERY);
  const [categories, setCategories] = useState([]);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selectedToDelete, setSelectedToDelete] = useState(null);
  const [deleting, setDeleting] = useState(false);

  const canSearch = useMemo(() => query.search.trim().length > 0, [query.search]);
  const canClearFilters = useMemo(
    () => canSearch || Boolean(query.categoryId),
    [canSearch, query.categoryId],
  );

  const load = async (nextQuery = query) => {
    setLoading(true);
    setError("");

    try {
      const response = await api.list(nextQuery);
      setData(response);
    } catch (err) {
      setError(err.message || "Falha ao carregar eventos");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query.page, query.size, query.sortBy, query.sortDir, query.categoryId]);

  useEffect(() => {
    const loadCategories = async () => {
      try {
        const options = await api.options();
        setCategories(options?.categories || []);
      } catch {
        // Falha no carregamento das categorias não bloqueia a listagem de eventos.
      }
    };

    loadCategories();
  }, [api]);

  const handleSearchSubmit = (event) => {
    event.preventDefault();
    setQuery((prev) => ({ ...prev, page: 1 }));
    load({ ...query, page: 1 });
  };

  const handleClearSearch = () => {
    const nextQuery = { ...query, search: "", categoryId: "", page: 1 };
    setQuery(nextQuery);
    load(nextQuery);
  };

  const handleDelete = async () => {
    if (!selectedToDelete) {
      return;
    }

    setDeleting(true);

    try {
      await api.remove(selectedToDelete.id);
      setSelectedToDelete(null);
      await load();
    } catch (err) {
      setError(err.message || "Falha ao excluir evento");
    } finally {
      setDeleting(false);
    }
  };

  return (
    <Stack spacing={3}>
      <Stack direction="row" alignItems="center" justifyContent="space-between">
        <Typography variant="h4">Eventos</Typography>
        <Button variant="contained" component={RouterLink} to="/events/new">
          Novo evento
        </Button>
      </Stack>

      <Paper sx={{ p: 2 }}>
        <Stack component="form" direction={{ xs: "column", md: "row" }} spacing={2} onSubmit={handleSearchSubmit}>
          <TextField
            label="Buscar por título"
            value={query.search}
            onChange={(event) => setQuery((prev) => ({ ...prev, search: event.target.value }))}
            fullWidth
          />

          <FormControl sx={{ minWidth: 180 }}>
            <InputLabel id="sort-by-label">Ordenar por</InputLabel>
            <Select
              labelId="sort-by-label"
              label="Ordenar por"
              value={query.sortBy}
              onChange={(event) => setQuery((prev) => ({ ...prev, sortBy: event.target.value, page: 1 }))}
            >
              <MenuItem value="startDate">Data de início</MenuItem>
              <MenuItem value="createdAt">Data de criação</MenuItem>
            </Select>
          </FormControl>

          <FormControl sx={{ minWidth: 140 }}>
            <InputLabel id="sort-dir-label">Direção</InputLabel>
            <Select
              labelId="sort-dir-label"
              label="Direção"
              value={query.sortDir}
              onChange={(event) => setQuery((prev) => ({ ...prev, sortDir: event.target.value, page: 1 }))}
            >
              <MenuItem value="asc">Crescente</MenuItem>
              <MenuItem value="desc">Decrescente</MenuItem>
            </Select>
          </FormControl>

          <FormControl sx={{ minWidth: 220 }}>
            <InputLabel id="category-filter-label">Categoria</InputLabel>
            <Select
              labelId="category-filter-label"
              label="Categoria"
              value={query.categoryId || ""}
              onChange={(event) =>
                setQuery((prev) => ({
                  ...prev,
                  categoryId: event.target.value,
                  page: 1,
                }))
              }
            >
              <MenuItem value="">Todas</MenuItem>
              {categories.map((category) => (
                <MenuItem key={category.id} value={category.id}>
                  {category.name}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <Button type="submit" variant="contained">Buscar</Button>
          <Button type="button" variant="text" disabled={!canClearFilters} onClick={handleClearSearch}>
            Limpar
          </Button>
        </Stack>
      </Paper>

      {error && <Alert severity="error">{error}</Alert>}

      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Título</TableCell>
              <TableCell>Data início</TableCell>
              <TableCell>Data término</TableCell>
              <TableCell>Categoria</TableCell>
              <TableCell>Status</TableCell>
              <TableCell>Organizador</TableCell>
              <TableCell align="right">Ações</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {loading && (
              <TableRow>
                <TableCell colSpan={7}>
                  <Box sx={{ display: "flex", justifyContent: "center", py: 3 }}>
                    <CircularProgress size={24} />
                  </Box>
                </TableCell>
              </TableRow>
            )}

            {!loading && data?.items?.length === 0 && (
              <TableRow>
                <TableCell colSpan={7}>Nenhum evento encontrado.</TableCell>
              </TableRow>
            )}

            {!loading &&
              data?.items?.map((event) => (
                <TableRow key={event.id} hover>
                  <TableCell>{event.title}</TableCell>
                  <TableCell>{toDisplayDateTime(event.startDate)}</TableCell>
                  <TableCell>{toDisplayDateTime(event.endDate)}</TableCell>
                  <TableCell>{event.category?.name || "Sem categoria"}</TableCell>
                  <TableCell>{event.status?.name || "-"}</TableCell>
                  <TableCell>{event.user?.email || "-"}</TableCell>
                  <TableCell align="right">
                    <Stack direction="row" spacing={1} justifyContent="flex-end">
                      <Button size="small" onClick={() => navigate(`/events/${event.id}`)}>
                        Ver
                      </Button>
                      <Button size="small" onClick={() => navigate(`/events/${event.id}/edit`)}>
                        Editar
                      </Button>
                      <Button
                        size="small"
                        color="error"
                        onClick={() => setSelectedToDelete(event)}
                      >
                        Excluir
                      </Button>
                    </Stack>
                  </TableCell>
                </TableRow>
              ))}
          </TableBody>
        </Table>

        <TablePagination
          component="div"
          rowsPerPageOptions={[5, 10, 20]}
          count={data?.totalItems || 0}
          rowsPerPage={query.size}
          page={(query.page || 1) - 1}
          onPageChange={(_, newPage) => setQuery((prev) => ({ ...prev, page: newPage + 1 }))}
          onRowsPerPageChange={(event) =>
            setQuery((prev) => ({ ...prev, size: Number(event.target.value), page: 1 }))
          }
        />
      </TableContainer>

      <Dialog open={Boolean(selectedToDelete)} onClose={() => setSelectedToDelete(null)}>
        <DialogTitle>Confirmar exclusão</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Deseja excluir o evento "{selectedToDelete?.title}"?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSelectedToDelete(null)} disabled={deleting}>Cancelar</Button>
          <Button onClick={handleDelete} color="error" disabled={deleting}>
            {deleting ? "Excluindo..." : "Excluir"}
          </Button>
        </DialogActions>
      </Dialog>
    </Stack>
  );
}
