// frontend-vue/src/App.vue
<template>
  <v-app>
    <v-app-bar color="indigo" density="comfortable" dark>
      <v-app-bar-title>TeamMeet Planner (Vue + Vuetify)</v-app-bar-title>
    </v-app-bar>
    <v-main class="d-flex align-center justify-center">
      <v-container class="py-12" style="max-width: 720px;">
        <v-card elevation="6" class="pa-6">
          <v-card-title class="text-h5 mb-2">Frontend ABs</v-card-title>
          <v-card-text>
            <p class="mb-4">
              Este é o frontend A do experimento. Use o botão abaixo para testar a API NestJS conectada ao MySQL.
            </p>
            <v-btn color="primary" @click="testApi" :loading="loading">
              Testar API
            </v-btn>
            <div class="mt-4" v-if="response">
              <v-alert type="success" variant="tonal" v-if="response.status === 'ok'">
                API respondeu: {{ response }}
              </v-alert>
              <v-alert type="error" variant="tonal" v-else>
                Erro ao chamar API: {{ response }}
              </v-alert>
            </div>
          </v-card-text>
        </v-card>
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup>
import { ref } from 'vue';

const loading = ref(false);
const response = ref(null);
const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';

async function testApi() {
  loading.value = true;
  try {
    const res = await fetch(`${apiUrl}/health`);
    const data = await res.json();
    response.value = data.data;
  } catch (error) {
    response.value = { status: 'error', message: error.message };
  } finally {
    loading.value = false;
  }
}
</script>

// frontend-react/src/App.jsx
import { useState } from 'react';
import { AppBar, Toolbar, Typography, Container, Card, CardContent, Button, Alert, CircularProgress } from '@mui/material';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';

function App() {
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);

  const testApi = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${apiUrl}/health`);
      const data = await res.json();
      setResponse(data);
    } catch (error) {
      setResponse({ status: 'error', message: error.message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <AppBar position="static" color="primary">
        <Toolbar>
          <Typography variant="h6" component="div">HelpDesk Lite (React + MUI)</Typography>
        </Toolbar>
      </AppBar>
      <Container maxWidth="sm" sx={{ mt: 6 }}>
        <Card elevation={6}>
          <CardContent>
            <Typography variant="h5" gutterBottom>Frontend B</Typography>
            <Typography paragraph>
              Este é o frontend B do experimento. Clique no botão para testar a API NestJS conectada ao MySQL.
            </Typography>
            <Button variant="contained" onClick={testApi} disabled={loading} startIcon={loading ? <CircularProgress size={18} color="inherit" /> : null}>
              {loading ? 'Chamando...' : 'Testar API'}
            </Button>
            {response && (
              <Alert severity={response.status === 'ok' ? 'success' : 'error'} sx={{ mt: 3 }}>
                {JSON.stringify(response)}
              </Alert>
            )}
          </CardContent>
        </Card>
      </Container>
    </>
  );
}

export default App;
