// frontend-vue/src/pages/EventFormPage.vue
<template>
  <v-container class="py-8" style="max-width: 900px">
    <div class="d-flex align-center justify-space-between mb-4">
      <div>
        <div class="text-h5">
          {{ isEdit ? "Editar evento" : "Novo evento" }}
        </div>
        <div class="text-body-2 text-medium-emphasis">
          Preencha os dados do evento.
        </div>
      </div>
      <v-btn variant="text" :to="{ name: 'events-list' }">Voltar</v-btn>
    </div>

    <v-card elevation="4">
      <v-card-text>
        <v-alert v-if="error" type="error" variant="tonal" class="mb-4">
          {{ error }}
        </v-alert>

        <v-form ref="formRef" v-model="formValid" @submit.prevent="submit">
          <v-row>
            <v-col cols="12" md="8">
              <v-text-field
                v-model="form.title"
                label="Título"
                variant="outlined"
                :rules="rules.title"
                required
              />
            </v-col>
            <v-col cols="12" md="4">
              <v-select
                v-model="form.status"
                label="Status"
                variant="outlined"
                :items="statusItems"
                item-title="title"
                item-value="value"
                required
              />
            </v-col>

            <v-col cols="12" md="6">
              <v-text-field
                v-model="form.startDate"
                label="Data de início"
                type="datetime-local"
                variant="outlined"
                :rules="rules.startDate"
                required
              />
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="form.endDate"
                label="Data de término"
                type="datetime-local"
                variant="outlined"
                :rules="rules.endDate"
                required
              />
            </v-col>

            <v-col cols="12" md="6">
              <v-text-field
                v-model="form.organizerEmail"
                label="E-mail do organizador"
                variant="outlined"
                :rules="rules.organizerEmail"
                required
              />
            </v-col>

            <v-col cols="12" md="6">
              <v-text-field
                v-model="form.location"
                label="Local"
                variant="outlined"
                :rules="rules.location"
                required
              />
            </v-col>

            <v-col cols="12" md="6">
              <v-select
                v-model="form.categoryId"
                :items="categoryItems"
                item-title="title"
                item-value="value"
                label="Categoria (opcional)"
                variant="outlined"
                clearable
              />
            </v-col>
          </v-row>

          <div class="d-flex align-center justify-end gap-2">
            <v-btn variant="text" :to="{ name: 'events-list' }">Cancelar</v-btn>
            <v-btn color="primary" type="submit" :loading="saving">
              Salvar
            </v-btn>
          </div>
        </v-form>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { eventsApi } from "../services/eventsApi";
import { categoriesApi } from "../services/categoriesApi";
import { isoToLocalInput, localInputToIso } from "../utils/dateTime";

const route = useRoute();
const router = useRouter();

const id = computed(() => (route.params.id ? Number(route.params.id) : null));
const isEdit = computed(() => Number.isFinite(id.value) && id.value > 0);

const formRef = ref(null);
const formValid = ref(false);

const saving = ref(false);
const loading = ref(false);
const error = ref("");

const statusItems = [
  { title: "Agendado", value: "scheduled" },
  { title: "Cancelado", value: "canceled" },
];

const categories = ref([]);
const categoryItems = computed(() => [
  { title: "Sem categoria", value: null },
  ...categories.value.map((c) => ({ title: c.name, value: c.id })),
]);

const form = ref({
  title: "",
  startDate: "",
  endDate: "",
  location: "",
  organizerEmail: "",
  status: "scheduled",
  categoryId: null,
});

const rules = {
  title: [
    (v) => !!v || "Título é obrigatório.",
    (v) => v?.length >= 3 || "Mínimo de 3 caracteres.",
    (v) => v?.length <= 100 || "Máximo de 100 caracteres.",
  ],
  organizerEmail: [
    (v) => !!v || "E-mail é obrigatório.",
    (v) => /.+@.+\..+/.test(v) || "E-mail inválido.",
  ],
  location: [
    (v) => !!v || "Local é obrigatório.",
    (v) => v?.length <= 255 || "Máximo de 255 caracteres.",
  ],
  startDate: [(v) => !!v || "Data de início é obrigatória."],
  endDate: [
    (v) => !!v || "Data de término é obrigatória.",
    () => {
      const startIso = localInputToIso(form.value.startDate);
      const endIso = localInputToIso(form.value.endDate);
      if (!startIso || !endIso) return true;
      return (
        new Date(endIso).getTime() > new Date(startIso).getTime() ||
        "Término deve ser maior que início."
      );
    },
  ],
};

async function load() {
  if (!isEdit.value) return;
  loading.value = true;
  error.value = "";
  try {
    const data = await eventsApi.get(id.value);
    form.value = {
      title: data.title ?? "",
      startDate: isoToLocalInput(data.startDate),
      endDate: isoToLocalInput(data.endDate),
      location: data.location ?? "",
      organizerEmail: data.organizerEmail ?? "",
      status: data.status ?? "scheduled",
      categoryId: data.category?.id ?? data.categoryId ?? null,
    };
  } catch (e) {
    error.value = e?.message || "Erro ao carregar evento.";
  } finally {
    loading.value = false;
  }
}

async function submit() {
  error.value = "";

  const result = await formRef.value?.validate?.();
  if (result && result.valid === false) return;

  const dto = {
    title: form.value.title,
    startDate: localInputToIso(form.value.startDate),
    endDate: localInputToIso(form.value.endDate),
    location: form.value.location,
    organizerEmail: form.value.organizerEmail,
    status: form.value.status,
    categoryId: form.value.categoryId,
  };

  saving.value = true;
  try {
    const saved = isEdit.value
      ? await eventsApi.update(id.value, dto)
      : await eventsApi.create(dto);

    router.push({ name: "events-detail", params: { id: saved.id } });
  } catch (e) {
    error.value = e?.message || "Erro ao salvar evento.";
  } finally {
    saving.value = false;
  }
}

onMounted(() => {
  (async () => {
    try {
      categories.value = await categoriesApi.list();
    } catch {
      categories.value = [];
    }

    load();
  })();
});
</script>

<style scoped>
.gap-2 {
  gap: 8px;
}
</style>

// frontend-react/src/pages/EventFormPage.jsx
import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  AppBar,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Container,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  TextField,
  Toolbar,
  Typography,
} from "@mui/material";
import { Link as RouterLink, useNavigate, useParams } from "react-router-dom";
import {
  createEvent,
  getEvent,
  getEventOptions,
  updateEvent,
} from "../services/eventsApi";

function toDateTimeLocal(dateValue) {
  if (!dateValue) return "";
  const date = new Date(dateValue);
  const offset = date.getTimezoneOffset();
  const local = new Date(date.getTime() - offset * 60000);
  return local.toISOString().slice(0, 16);
}

function toIso(value) {
  if (!value) return "";
  return new Date(value).toISOString();
}

function validate(values) {
  const errors = {};
  if (!values.title || values.title.trim().length < 3 || values.title.trim().length > 100) {
    errors.title = "Título deve ter entre 3 e 100 caracteres.";
  }
  if (!values.organizerEmail || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.organizerEmail)) {
    errors.organizerEmail = "Informe um e-mail válido.";
  }
  if (!values.startDate || !values.endDate || toIso(values.endDate) <= toIso(values.startDate)) {
    errors.endDate = "Data de término deve ser maior que a data de início.";
  }
  if (!values.location || values.location.trim().length < 2) {
    errors.location = "Informe um local válido.";
  }
  if (!values.statusId) {
    errors.statusId = "Selecione um status.";
  }
  return errors;
}

export function EventFormPage({ mode }) {
  const navigate = useNavigate();
  const { id } = useParams();
  const editing = mode === "edit";

  const [loading, setLoading] = useState(editing);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [statusOptions, setStatusOptions] = useState([]);
  const [categoryOptions, setCategoryOptions] = useState([]);
  const [form, setForm] = useState({
    title: "",
    startDate: "",
    endDate: "",
    location: "",
    organizerEmail: "",
    organizerName: "",
    statusId: "",
    categoryId: "",
  });

  const validationErrors = useMemo(() => validate(form), [form]);

  useEffect(() => {
    const load = async () => {
      setError("");
      try {
        const options = await getEventOptions();
        setStatusOptions(options.statuses || []);
        setCategoryOptions(options.categories || []);

        if (editing && id) {
          const event = await getEvent(id);
          setForm({
            title: event.title || "",
            startDate: toDateTimeLocal(event.startDate),
            endDate: toDateTimeLocal(event.endDate),
            location: event.location || "",
            organizerEmail: event.organizerEmail || "",
            organizerName: event.organizerName || "",
            statusId: event.statusId || "",
            categoryId: event.category?.id ?? "",
          });
        } else if (!editing && options.statuses?.length) {
          setForm((current) => ({
            ...current,
            statusId: current.statusId || options.statuses[0].id,
          }));
        }
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [editing, id]);

  const handleChange = (field) => (event) => {
    setForm((current) => ({ ...current, [field]: event.target.value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    const errors = validate(form);
    if (Object.keys(errors).length > 0) return;

    setSaving(true);
    setError("");

    try {
      const payload = {
        title: form.title.trim(),
        startDate: toIso(form.startDate),
        endDate: toIso(form.endDate),
        location: form.location.trim(),
        organizerEmail: form.organizerEmail.trim(),
        organizerName: form.organizerName.trim() || undefined,
        statusId: Number(form.statusId),
        categoryId: form.categoryId ? Number(form.categoryId) : null,
      };

      if (editing && id) {
        await updateEvent(id, payload);
      } else {
        await createEvent(payload);
      }

      navigate("/eventos");
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Box>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            TeamMeet Planner
          </Typography>
          <Button color="inherit" component={RouterLink} to="/eventos">
            Voltar para lista
          </Button>
        </Toolbar>
      </AppBar>

      <Container maxWidth="md" sx={{ py: 4 }}>
        <Card>
          <CardContent>
            <Typography variant="h5" sx={{ mb: 3 }}>
              {editing ? "Editar evento" : "Novo evento"}
            </Typography>

            {loading ? (
              <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
                <CircularProgress />
              </Box>
            ) : (
              <Box component="form" onSubmit={handleSubmit}>
                <Stack gap={2}>
                  {error && <Alert severity="error">{error}</Alert>}

                  <TextField
                    required
                    label="Título"
                    value={form.title}
                    onChange={handleChange("title")}
                    error={Boolean(validationErrors.title)}
                    helperText={validationErrors.title}
                  />

                  <Stack direction={{ xs: "column", md: "row" }} gap={2}>
                    <TextField
                      required
                      type="datetime-local"
                      label="Data de início"
                      InputLabelProps={{ shrink: true }}
                      value={form.startDate}
                      onChange={handleChange("startDate")}
                      fullWidth
                    />
                    <TextField
                      required
                      type="datetime-local"
                      label="Data de término"
                      InputLabelProps={{ shrink: true }}
                      value={form.endDate}
                      onChange={handleChange("endDate")}
                      error={Boolean(validationErrors.endDate)}
                      helperText={validationErrors.endDate}
                      fullWidth
                    />
                  </Stack>

                  <TextField
                    required
                    label="Local"
                    value={form.location}
                    onChange={handleChange("location")}
                    error={Boolean(validationErrors.location)}
                    helperText={validationErrors.location}
                  />

                  <Stack direction={{ xs: "column", md: "row" }} gap={2}>
                    <TextField
                      required
                      type="email"
                      label="E-mail do organizador"
                      value={form.organizerEmail}
                      onChange={handleChange("organizerEmail")}
                      error={Boolean(validationErrors.organizerEmail)}
                      helperText={validationErrors.organizerEmail}
                      fullWidth
                    />
                    <TextField
                      label="Nome do organizador (opcional)"
                      value={form.organizerName}
                      onChange={handleChange("organizerName")}
                      fullWidth
                    />
                  </Stack>

                  <Stack direction={{ xs: "column", md: "row" }} gap={2}>
                    <FormControl fullWidth error={Boolean(validationErrors.statusId)}>
                      <InputLabel id="status-label">Status</InputLabel>
                      <Select
                        labelId="status-label"
                        label="Status"
                        value={form.statusId}
                        onChange={handleChange("statusId")}
                      >
                        {statusOptions.map((status) => (
                          <MenuItem key={status.id} value={status.id}>
                            {status.name}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>

                    <FormControl fullWidth>
                      <InputLabel id="category-label">Categoria</InputLabel>
                      <Select
                        labelId="category-label"
                        label="Categoria"
                        value={form.categoryId}
                        onChange={handleChange("categoryId")}
                      >
                        <MenuItem value="">Sem categoria</MenuItem>
                        {categoryOptions.map((category) => (
                          <MenuItem key={category.id} value={category.id}>
                            {category.name}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>
                  </Stack>

                  <Stack direction="row" justifyContent="flex-end" gap={1}>
                    <Button component={RouterLink} to="/eventos">
                      Cancelar
                    </Button>
                    <Button
                      type="submit"
                      variant="contained"
                      disabled={saving || Object.keys(validationErrors).length > 0}
                    >
                      {saving ? "Salvando..." : "Salvar"}
                    </Button>
                  </Stack>
                </Stack>
              </Box>
            )}
          </CardContent>
        </Card>
      </Container>
    </Box>
  );
}
