// frontend-vue/src/pages/HomePage.vue
<template>
  <v-container class="py-12" style="max-width: 720px;">
    <v-card elevation="6" class="pa-6">
      <v-card-title class="text-h5 mb-2">Frontend ABs</v-card-title>
      <v-card-text>
        <p class="mb-4">
          Este é o frontend A do experimento. Use o botão abaixo para testar a API NestJS conectada ao MySQL.
        </p>
        <v-btn color="primary" @click="testApi" :loading="loading">
          Testar API
        </v-btn>
        <div class="mt-4" v-if="response">
          <v-alert type="success" variant="tonal" v-if="response.status === 'ok'">
            API respondeu: {{ response }}
          </v-alert>
          <v-alert type="error" variant="tonal" v-else>
            Erro ao chamar API: {{ response }}
          </v-alert>
        </div>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref } from 'vue';

const loading = ref(false);
const response = ref(null);
const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000';

async function testApi() {
  loading.value = true;
  try {
    const res = await fetch(`${apiUrl}/health`);
    const data = await res.json();
    response.value = data.data;
  } catch (error) {
    response.value = { status: 'error', message: error.message };
  } finally {
    loading.value = false;
  }
}
</script>

// frontend-react/src/pages/HomePage.jsx
import { useMemo, useState } from "react";
import {
  Alert,
  AppBar,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Container,
  Toolbar,
  Typography,
} from "@mui/material";

const apiUrl = import.meta.env.VITE_API_URL || "http://localhost:3000";

const SAYINGS = [
  "Se der certo de primeira, desconfie.",
  "Nada é tão permanente quanto uma gambiarra temporária.",
  "Hoje vai. Amanhã também.",
  "Deploy na sexta? Coragem.",
  "Funciona na minha máquina.",
];

export function HomePage() {
  const saying = useMemo(() => {
    const index = Math.floor(Math.random() * SAYINGS.length);
    return SAYINGS[index];
  }, []);

  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);

  const testApi = async () => {
    setLoading(true);
    setResponse(null);

    try {
      const traceId = globalThis.crypto?.randomUUID?.();
      const res = await fetch(`${apiUrl}/health`,
        traceId ? { headers: { "x-trace-id": traceId } } : undefined,
      );

      const data = await res.json();
      setResponse({ ok: res.ok, status: res.status, data });
    } catch (error) {
      setResponse({ ok: false, status: 0, data: { message: error?.message } });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            Compare AI — React
          </Typography>
        </Toolbar>
      </AppBar>

      <Container maxWidth="sm" sx={{ py: 6 }}>
        <Card elevation={6}>
          <CardContent>
            <Typography variant="h4" gutterBottom>
              Página inicial
            </Typography>

            <Typography color="text.secondary" sx={{ mb: 3 }}>
              {saying}
            </Typography>

            <Button
              variant="contained"
              onClick={testApi}
              disabled={loading}
              startIcon={loading ? <CircularProgress size={18} color="inherit" /> : null}
            >
              {loading ? "Chamando /health..." : "Testar /health do backend"}
            </Button>

            {response && (
              <Alert
                sx={{ mt: 3, wordBreak: "break-word" }}
                severity={response.ok ? "success" : "error"}
              >
                {JSON.stringify(response)}
              </Alert>
            )}

            <Typography variant="body2" color="text.secondary" sx={{ mt: 3 }}>
              API: {apiUrl}
            </Typography>
          </CardContent>
        </Card>
      </Container>
    </Box>
  );
}
